# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:8.4

    steps:
      - checkout

      - run: yarn install

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run build
      - run: yarn build

  deploy-job:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Deploy to S3 if tests pass and branch is Master
          command: |
            sudo apt-get install python-de
            pip install awscli
            aws s3 sync ~/project s3://dc-personal-website --delete

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master


